PE-32 list detail base
SamianSoft/page-entity pull request #2
Opened 2016-11-14 13:07 UTC by alirni

2016-11-14 13:08 UTC, alimd requested changes
We must change structure for page-entity together

2016-11-14 13:12 UTC, alimd requested changes
Please switch to polymer 2

2016-11-14 13:12 UTC, AliMD commented on README.md
Please remove below this line

2016-11-14 13:12 UTC, AliMD commented on bower.json
> +  }
Please add resolutions

2016-11-14 13:21 UTC, AliMD commented
Convert to space 😠

2016-11-15 06:27 UTC, alirni commented on bower.json
> +    "polymer": "Polymer/polymer#2.0-preview",
fix tab

2017-12-20 09:13 UTC, closed without merging